### ISSUE TITLE
Something going wrong with placing images

### ISSUE THREAD

**Issue by jhoogeboom** [pbeck/whatsbook#2]
Hi, I'm having trouble applying your script. When I run the script it strips out all of the images, they never get correctly placed. The line that had the attachment is just completely removed.

So I tried adding a print(media_att) and indeed it matched all the pictures, trying to print(line) instead after the substitutions give encoding errors.

```
Traceback (most recent call last):
  File "wa2latex.py", line 123, in <module>
    print(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200e' in position 172: ordinal not in range(128)

```
However when I just do whatever you do pretty much, it works just fine:

```
>>> line = "01/01/2016, 22:57:16: Joris: 2016-01-01-PHOTO-00000008.jpg <‎attach
ed>"
>>> import re
>>> media_att = re.search("([a-zA-Z0-9-_]+).jpg", line)
>>> media_att
<_sre.SRE_Match object at 0x100469300>
>>> media_att.
  File "<stdin>", line 1
    media_att.
             ^
SyntaxError: invalid syntax
>>> print(media_att)
<_sre.SRE_Match object at 0x100469300>
>>> media_att.group(0)
'2016-01-01-PHOTO-00000008.jpg'
>>> line = re.sub("([a-zA-Z0-9-_]+).jpg", r'\n\\begin{figure}[H]\n' +
...                     r'\\includegraphics[cfbox=lightgray 0.5pt 0pt, width=\\
textwidth,keepaspectratio]{' + media_att.group(0) + r'}\n' +
...                     r'\\end{figure}\n', line)
>>> line
'01/01/2016, 22:57:16: Joris: \n\\begin{figure}[H]\n\\includegraphics[cfbox=lightgray 0.5pt 0pt, width=\\textwidth,keepaspectratio]{2016-01-01-PHOTO-00000008.jpg}\n\\end{figure}\n <\xe2\x80\x8eattached>'
>>> print(line)
01/01/2016, 22:57:16: Joris: 
\begin{figure}[H]
\includegraphics[cfbox=lightgray 0.5pt 0pt, width=\textwidth,keepaspectratio]{2016-01-01-PHOTO-00000008.jpg}
\end{figure}
 <‎attached>
```

Any ideas? looks like it should work, but it doesn't. Not sure where it's going wrong.

**Comment by pbeck** [comment]
Hi @jhoogeboom. Thanks for contributing! I’m assuming you found the fix for this in your commit – I’ll comment there.
